spring.application.name=kafka-standby
# set spring-web port to 8081
server.port=8081

spring.kafka.bootstrap-servers=localhost:9092
spring.kafka.consumer.group-id=kafka-standby-group
spring.kafka.consumer.auto-offset-reset=earliest
spring.kafka.consumer.key-deserializer=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.consumer.value-deserializer=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.apache.kafka.common.serialization.StringSerializer

unleash.url=http://localhost:4242/api/
unleash.apiKey=default:development.unleash-insecure-api-token
unleash.appName=unleash-onboarding-java
unleash.instanceId=unleash-onboarding-instance
