---
version: '2'
services:
  akhq:
    image: tchiotludo/akhq
    security_opt:
      - seccomp:unconfined
    environment:
      AKHQ_CONFIGURATION: |
        akhq:
          connections:
            docker-kafka-server:
              properties:
                bootstrap.servers: "broker:29092"
              schema-registry:
                url: "http://schema-registry:8081"
              connect:
                - name: "connect"
                  url: "http://connect:8083"
      JAVA_OPTS: -XX:MaxRAM=250M
    ports:
      - 8089:8080
    links:
      - broker
      - schema-registry

# should you need more control over the JVM options, you can mount the config file
# in case of errors with this file make sure it is not using Windows line endings
# you can convert it with `dos2unix` and check with `file akhq-jvm.options` => this should return ASCII text and not ASCII text, with CRLF line terminators
#    volumes:
#      - ./akhq-jvm.options:/app/jvm.options
