name: Build aggregator

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: maven

      - name: Cache Maven packages
        uses: actions/cache@v3
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2

      - name: root build with maven
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Needed to get PR information, if any
        run: mvn -B clean verify

      - name: Build with maven java-consumer
        working-directory: kafka-exercises-solutions/3.1-java-client/java-consumer
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Needed to get PR information, if any
        run: mvn -B clean verify

      - name: Build with maven java-producer
        working-directory: kafka-exercises-solutions/3.1-java-client/java-producer
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Needed to get PR information, if any
        run: mvn -B clean verify

      - name: Build with maven quarkus-consume-call-rest
        working-directory: kafka-exercises-solutions/4.1-quarkus/quarkus-consume-call-rest
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Needed to get PR information, if any
        run: mvn -B clean verify

      - name: Build with maven quarkus-producer-from-rest
        working-directory: kafka-exercises-solutions/4.1-quarkus/quarkus-producer-from-rest
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Needed to get PR information, if any
        run: mvn -B clean verify

      - name: Build with maven java-avro-producer
        working-directory: kafka-exercises-solutions/6.2-java-avro-clients/java-avro-producer
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Needed to get PR information, if any
        run: mvn -B clean verify

      - name: Build with maven quarkus-avro-consumer
        working-directory: kafka-exercises-solutions/6.2-java-avro-clients/quarkus-avro-consumer
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Needed to get PR information, if any
        run: mvn -B clean verify
